test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -24,9 +24,16 @@ parameters:
 jobs:
   integration-test:
     docker:
-      - image: cimg/php:7.4
+      - image: php:7.4
     steps:
+      - run:
+          name: Install PCOV and git
+          command: |-
+            apk add --update --no-cache ${PHPIZE_DEPS}
+            pecl install pcov-1.0.6
+            docker-php-ext-enable pcov
       - checkout
+      - composer/install_bin
       - composer/install:
           working-dir: tests
       # Normal test
@@ -40,11 +47,13 @@ jobs:
           coverage-format: clover
           coverage-path: coverage/clover.xml
           path: tests/FooTest.php
-      - run: |-
-          if [ ! -f "coverage/clover.xml" ]; then
-            echo 'Test failed, "coverage/clover.xml" does not exist'
-            circleci-agent step halt
-          fi
+      - run:
+          name: Assert code coverage
+          command: |-
+            if [ ! -f "coverage/clover.xml" ]; then
+              echo 'Test failed, "coverage/clover.xml" does not exist'
+              exit 1
+            fi
 
 workflows:
   test-pack:
